### ISSUE TITLE
Weird conflict with Twitter feed widget (body disappearing)

### ISSUE THREAD

**Issue by chrisblakley** [FrDH/jQuery.mmenu#969]
I ran into a strange conflict where my Twitter feed widget was appearing and then quickly disappearing. I'm currently using Mmenu version 7.2.2, but I have tested it with 7.2.3 and it is still occurring.

When the Twitter feed disappears I can see that inside of the iframe, the body tag is empty, so: `<body></body>`.

![screen shot 2019-02-14 at 5 05 16 pm](https://user-images.githubusercontent.com/6349678/52820716-bb6ae900-307a-11e9-9783-32708bdcca7d.png)

After chasing it around for a while I found that it was the `.mmenu()` function that was causing it. I don't know what specifically in there is the problem, but when I revert to Mmenu version 6.1.8 it works as expected.

I am calling the `.mmenu()` function from window load if that helps diagnosis this at all. Technically, I'm lazyloading the script by waiting for window load then `GET`ing all.js from CDNJS then calling the function which runs the Mmenu logic. I'll see if I can create an eloborate Codepen to try to recreate this setup.

Here's the Twitter widget code for reference:
```
<a class="twitter-timeline" data-lang="en" data-height="800" data-link-color="#00a1d6" href="https://twitter.com/PinckneyHugo?ref_src=twsrc%5Etfw">Tweets by Pinckney Hugo Group</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

Edit: I'm having difficulty recreating this. On Codepen it works fine even with my convoluted lazyloading... https://codepen.io/chrisblakley/pen/rPqOYg

The problem is visible here (or rather, invisible) under the sidebar on the right side:
https://gearside.com/nebula/get-started/checklists/

**Comment by chrisblakley** [comment]
I don't know why this triggers when `mmenu()` is called, but it seems like it's actually a conflict with Query Monitor (WordPress plugin).

For some reason, the Twitter Feed widget appears to be super fragile. I'm closing this issue, but more of my troubleshooting notes are here (on the slim chance someone else has this same problem): https://github.com/chrisblakley/Nebula/issues/1820

**Comment by chrisblakley** [comment]
Sorry, this is so difficult to troubleshoot. Deactivating Query Monitor on one site worked fine, but not on another site– when I either block `mmenu.all.js` or don't call `mmenu()` the Twitter widget works, so it may be worth looking into.

**Comment by chrisblakley** [comment]
Using local overrides in Chrome Devtools, I was able to narrow it down to this line in `mmenu.all.js` of 7.2.3
https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/7.2.3/jquery.mmenu.all.js

```js
this.setPage(a.$page),
```

This line is inside of an event that listens for `initMenu:after`

Not sure if this is helpful, but for reference:
![screen shot 2019-02-15 at 4 56 50 pm](https://user-images.githubusercontent.com/6349678/52886577-be311100-3142-11e9-8de5-5d48dd649782.png)

The commented out line is the troublemaker (note: I've swapped out the `,` for `;` in this function.

But I was working from a minified file, so the next step would be to figure out what the unminified line actually is (which I have not had time to do yet).

**Comment by FrDH** [comment]
Give this page a try:
http://www.mmenujs.com/tutorials/off-canvas/the-page.html

It explains how most issues with widgets and such can be prevented.

**Comment by chrisblakley** [comment]
Thanks, I'll double-check that. I've been using Mmenu in my theme for a few years now without an issue, but I'll make sure nothing has changed in the page layout itself (particularly for version 7).

**Comment by chrisblakley** [comment]
I double-checked my code and I still have my `<div id="body-wrapper">` inside the body tag. The only styles applied to it is the `will-change` property:
https://github.com/chrisblakley/Nebula/search?q=body-wrapper&unscoped_q=body-wrapper

In the meantime I can continue to poke around to see exactly what inside the `setPage` is conflicting.

**Comment by chrisblakley** [comment]
I played around with this some more tonight, and I think you're right that it has *something* to do with the page wrapper because I've narrowed it down to a conditional that checks `conf.page.wrapIfNeeded` which seems to imply that Mmenu isn't detecting that my page is properly wrapped (I'm guessing based on the property name). The next function is a `.wrapAll()` that is adding a `<div>`.

https://github.com/FrDH/jQuery.mmenu/blob/210244a32c3c8e29ed33b0e6812b289ff85f0e03/src/core/offcanvas/jquery.mmenu.offcanvas.ts#L420-L425

So I think you're exactly right on this, but I can't seem to figure out what my issue is. So it doesn't seem like any action is needed on your part, but if you happen to think of any tips/ideas I'd be happy to hear them.

**Comment by chrisblakley** [comment]
Ok, I figured out exactly what was happening. This may be relevant to other WordPress users. The Query Monitor plugin adds a `<div>` for their debugging interface which is dynamically placed outside of `wp_footer()`. This means that Mmenu will determine that it needs to wrap the body content itself and causes the Twitter feed widget to disappear.

I don't have a resolution to this, but I'm hoping that Query Monitor can modify where the debug interface is placed.

I know Mmenu has a WordPress plugin option– is there a chance this could be tested there? I'm curious if there are other workarounds outside of expecting Query Monitor to change how they are implementing their interface.

**Comment by FrDH** [comment]
I think this could be due to a bug in 7.3.0, should be fixed in 7.3.1

**Comment by chrisblakley** [comment]
I just upgraded to 7.3.1 and gave it a try with no luck– if there is any more detail I can provide to help I'm happy to do some more digging.

**Comment by FrDH** [comment]
This is embarrassing, 7.3.1 did not compile new .js files :/
Please try 7.3.2

**Comment by chrisblakley** [comment]
Hmm, still no luck- I also tried it incognito to ensure I wasn't cached in. I believe the particular issue I'm running into has been happening since version 7.1 and I just never ran into this exact combination of libraries until last week.

I just tried each version that was available on CDNJS and without changing my config code, version 7.0.6 is the last version to work.

**Comment by FrDH** [comment]
The config option changed:
https://mmenujs.com/documentation/core/off-canvas.html

````js
offCanvas: {
   page: {
      selector: "#body-wrapper"
   }
}
````

**Comment by chrisblakley** [comment]
That fixed it. Sorry I did not notice that change– thanks so much for the clarification!

**Comment by FrDH** [comment]
No problem, the need for wrapping the HTML is the biggest drawback of the plugin.
If you can, please include the "debugger" script if you ever run into an issue or bug. It should have logged a warning about the changed option to the console.
